Q3. Singular Value Decomposition (SVD):


In [1]:
import numpy as np

# Set random seed
np.random.seed(37)

# Create a random 5x5 matrix A with integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

Original Matrix A:
[[5 6 3 3 5]
 [8 5 7 8 8]
 [3 2 8 1 8]
 [3 8 4 1 3]
 [2 3 3 2 9]]


In [2]:
# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)

In [3]:
# Construct Σ matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape), :min(A.shape)] = np.diag(S)

In [4]:
# Print U, Σ, and Vt matrices
print("\nMatrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix Vt:")
print(Vt)


Matrix U:
[[-0.3923064  -0.36919074  0.05394074  0.24946297 -0.80290255]
 [-0.63291839 -0.11812009 -0.7023484  -0.11805569  0.27969902]
 [-0.43391378  0.59794268  0.29837795 -0.56358917 -0.21799363]
 [-0.33848155 -0.57163619  0.5960153  -0.18877498  0.40962431]
 [-0.37770236  0.40674619  0.24399485  0.75535576  0.24860139]]

Matrix Σ:
[[24.95995858  0.          0.          0.          0.        ]
 [ 0.          6.95652574  0.          0.          0.        ]
 [ 0.          0.          5.60455046  0.          0.        ]
 [ 0.          0.          0.          3.79003016  0.        ]
 [ 0.          0.          0.          0.          0.91208703]]

Matrix Vt:
[[-0.40454674 -0.40974497 -0.46336982 -0.31122112 -0.59739503]
 [-0.27290958 -0.71338922  0.25628057 -0.17433042  0.56614958]
 [-0.38859745  0.51900064  0.13354376 -0.72701317  0.18234105]
 [-0.11702061  0.14120955 -0.81153628  0.14836049  0.53456906]
 [-0.7727616   0.18407357  0.20780668  0.567619   -0.0598455 ]]


In [5]:
# Verify that A equals the product of U, Σ, and Vt
A_reconstructed = np.dot(U, np.dot(Sigma, Vt))
print("\nReconstructed Matrix A:")
print(A_reconstructed)


Reconstructed Matrix A:
[[5. 6. 3. 3. 5.]
 [8. 5. 7. 8. 8.]
 [3. 2. 8. 1. 8.]
 [3. 8. 4. 1. 3.]
 [2. 3. 3. 2. 9.]]


In [6]:
# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(Sigma[:2, :2], Vt[:2, :]))
print("\nRank 2 Approximation of Matrix A:")
print(rank_2_approximation)


Rank 2 Approximation of Matrix A:
[[4.66221157 5.84438954 3.87909325 3.49519231 4.39562976]
 [6.61512558 7.05918972 7.10955162 5.05980027 8.97220955]
 [3.24623562 1.47031418 6.08453855 2.6455256  8.8250269 ]
 [4.50305998 6.29858928 2.89564734 3.3225898  2.79573173]
 [3.04162955 1.84428062 5.09354522 2.44074207 7.23384613]]


In [7]:
# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(Sigma[:3, :3], Vt[:3, :]))
print("\nRank 3 Approximation of Matrix A:")
print(rank_3_approximation)


Rank 3 Approximation of Matrix A:
[[4.54473327 6.00129051 3.91946535 3.27540633 4.45075395]
 [8.14478002 5.01622306 6.58387703 7.92157643 8.25445189]
 [2.5963941  2.3382256  6.30786035 1.42976018 9.12995115]
 [3.20498989 8.03225791 3.34173663 0.89407658 3.40482338]
 [2.51022975 2.55400437 5.27616384 1.44656506 7.48319413]]
